### ISSUE TITLE
[Solved]VPS setup plz

### ISSUE THREAD

**Issue by tehseensagar** [anirudhmalik/xhunter-server#1]
Greetings,

Good to see that you have developed it on heroku. My concern is to configure it on my remote server could please guide/assist me to setup back end server. 

Regards

**Comment by anirudhmalik** [comment]
> Greetings,
> 
> Good to see that you have developed it on heroku. My concern is to configure it on my remote server could please guide/assist me to setup back end server. 
> 
> Regards

If you have your remote server that you can just use  `custom server` option in xhunter.apk. how to  configure your ubuntu server see here--> #18.
But if you still want to host `xhunter-server`  that install node on your server/vps.
- clone repo `git clone https://github.com/anirudhmalik/xhunter-server`
- `cd xhunter-server` 
- `npm install`
- `node start time ndex.js`

Then check http://<your_server_ip>:8080

**Comment by tehseensagar** [comment]
> > Greetings,
> > Good to see that you have developed it on heroku. My concern is to configure it on my remote server could please guide/assist me to setup back end server.
> > Regards
> 
> If you have your remote server then you can just use `custom server` option in xhunter.apk. how to configure your ubuntu server see here--> [anirudhmalik/xhunter#18](https://github.com/anirudhmalik/xhunter/discussions/18). But if you still want to host `xhunter-server` then install node on your server/vps.
> 
>     * clone repo `git clone https://github.com/anirudhmalik/xhunter-server`
> 
>     * `cd xhunter-server`
> 
>     * `npm install`
> 
>     * `node  index.js`
> 
> 
> Then check http://<your_server_ip>:8080

well I have npm  version
`8.1.0`

node version
`v16.12.0`


When running node index.js 
`node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /opt/xhunter/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/xhunter/index.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/xhunter/index.js' ]
`

Hope to hear from you .

Regards

**Comment by tehseensagar** [comment]
> > > Greetings,
> > > Good to see that you have developed it on heroku. My concern is to configure it on my remote server could please guide/assist me to setup back end server.
> > > Regards
> > 
> > 
> > If you have your remote server then you can just use `custom server` option in xhunter.apk. how to configure your ubuntu server see here--> [anirudhmalik/xhunter#18](https://github.com/anirudhmalik/xhunter/discussions/18). But if you still want to host `xhunter-server` then install node on your server/vps.
> > ```
> > * clone repo `git clone https://github.com/anirudhmalik/xhunter-server`
> > 
> > * `cd xhunter-server`
> > 
> > * `npm install`
> > 
> > * `node  index.js`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then check http://<your_server_ip>:8080
> 
> well I have npm version `8.1.0`
> 
> node version `v16.12.0`
> 
> When running node index.js
> 
> `node:internal/modules/cjs/loader:936` ` throw err;` ` ^` `Error: Cannot find module 'express'` `Require stack:` `- /opt/xhunter/index.js` ` at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)` ` at Function.Module._load (node:internal/modules/cjs/loader:778:27)` ` at Module.require (node:internal/modules/cjs/loader:1005:19)` ` at require (node:internal/modules/cjs/helpers:102:18)` ` at Object.<anonymous> (/opt/xhunter/index.js:1:17)` `at Module._compile (node:internal/modules/cjs/loader:1101:14)` `at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)` `at Module.load (node:internal/modules/cjs/loader:981:32)` `at Function.Module._load (node:internal/modules/cjs/loader:822:12)` `at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {` `code: 'MODULE_NOT_FOUND',` `requireStack: [ '/opt/xhunter/index.js' ]`
> 
> Hope to hear from you .
> 
> Regards

Error is fixed by installing module express

`npm install express`
